version: '{build}'

skip_tags: true
skip_branch_with_pr: true
clone_depth: 1
deploy: off
build: off

install:
  - ps: Install-Product node '10'
  - npm ci

test_script:
  - npm test

cache:
  - '%APPDATA%\npm-cache'
